name: NUnit Documentation Build Process

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build_docfx:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Run spell check
        with:
          node-version: '12'
      - run: npm install -g cspell
      - run: cspell --config ./cSpell.json "docs/**/*.md"
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.2.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DISABLE_ERRORS: true
      - uses: nikeee/docfx-action@master
        name: Build with Docfx
        with:
          args: docs/docfx.json --warningsAsErrors true
      - name: Push to gh-pages branch (master only)
        if: ${{ github.ref == 'refs/heads/master'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          publish_branch: gh-pages
